import { ArrowUpRight, Building2, MapPin, Users } from 'lucide-react';
import { Link } from 'wouter';
import { getListBranchesQueryKey, useListBranches } from '@workspace/api-client-react';
import { EmptyState, ErrorState, LoadingRows, PageHeader } from '@/components/ui';

export default function BranchesPage() {
  const branchesQuery = useListBranches({ query: { queryKey: getListBranchesQueryKey() } });
  const branches = branchesQuery.data ?? [];
  const totalMembers = branches.reduce((sum, branch) => sum + branch.memberCount, 0);
  const avgRate = branches.length ? branches.reduce((sum, branch) => sum + branch.collectionRate, 0) / branches.length : 0;
  return <div className="content-wrap page-enter">
    <PageHeader eyebrow="The network behind the records" title="Branch coverage" description="See where members are supported and how consistently contributions are arriving." actions={<Link href="/members" data-testid="link-branch-members" className="btn btn-secondary"><Users size={15} /> Browse members</Link>} />
    <div className="grid md:grid-cols-3 gap-4 mb-5"><div className="card stat-card"><div className="stat-label">Active branches</div><div className="stat-value" data-testid="value-branch-count">{branches.length}</div><div className="text-xs text-muted-foreground mt-2">Across the scheme</div></div><div className="card stat-card"><div className="stat-label">Members covered</div><div className="stat-value" data-testid="value-branch-members">{totalMembers}</div><div className="text-xs text-muted-foreground mt-2">People in branch records</div></div><div className="card stat-card"><div className="stat-label">Average collection</div><div className="stat-value" data-testid="value-branch-rate">{avgRate.toFixed(1)}%</div><div className="text-xs text-muted-foreground mt-2">This month</div></div></div>
    <div className="grid md:grid-cols-2 gap-5">{branchesQuery.isLoading ? <LoadingRows count={4} /> : branchesQuery.isError ? <div className="card md:col-span-2"><ErrorState onRetry={() => branchesQuery.refetch()} /></div> : branches.length === 0 ? <div className="card md:col-span-2"><EmptyState title="No branches configured" description="Branch coverage will appear here once locations are added." /></div> : branches.map((branch) => <section className="card p-5" key={branch.id} data-testid={`card-branch-${branch.id}`}><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-secondary grid place-items-center text-primary"><Building2 size={18} /></div><div><div className="font-bold">{branch.name}</div><div className="text-xs text-muted-foreground flex items-center gap-1 mt-1"><MapPin size={12} /> {branch.location}</div></div></div><Link href="/members" data-testid={`button-branch-menu-${branch.id}`} className="btn btn-ghost p-2"><ArrowUpRight size={15} /></Link></div><div className="grid grid-cols-2 gap-4 mt-6"><div><div className="text-[10px] text-muted-foreground uppercase tracking-wider">Members</div><div className="text-xl font-bold mt-1">{branch.memberCount}</div></div><div><div className="text-[10px] text-muted-foreground uppercase tracking-wider">Collection</div><div className="text-xl font-bold mt-1">{branch.collectionRate.toFixed(1)}%</div></div></div><div className="mini-bar mt-5"><span style={{ width: `${Math.min(branch.collectionRate, 100)}%` }} /></div><div className="flex justify-between mt-2 text-[11px] text-muted-foreground"><span>Monthly collection health</span><span>{branch.collectionRate >= 85 ? 'On track' : 'Follow-up needed'}</span></div></section>)}</div>
  </div>;
}
