import { CircleDollarSign, Plus, Search, SlidersHorizontal } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { ContributionStatus, getListContributionsQueryKey, getListMembersQueryKey, useListContributions, useListMembers, useRecordContribution } from '@workspace/api-client-react';
import type { ContributionInput } from '@workspace/api-client-react';
import { EmptyState, ErrorState, formatCurrency, formatDate, LoadingRows, Modal, PageHeader, StatusBadge } from '@/components/ui';

export default function ContributionsPage() {
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const [open, setOpen] = useState(false);
  const queryClient = useQueryClient();
  const params = useMemo(() => ({ status: (status || undefined) as ContributionStatus | undefined }), [status]);
  const contributionsQuery = useListContributions(params, { query: { queryKey: getListContributionsQueryKey(params) } });
  const membersQuery = useListMembers(undefined, { query: { queryKey: getListMembersQueryKey() } });
  const recordContribution = useRecordContribution();
  const contributions = (contributionsQuery.data ?? []).filter((item) => item.memberName.toLowerCase().includes(search.toLowerCase()) || item.memberId.toLowerCase().includes(search.toLowerCase()));
  return <div className="content-wrap page-enter">
    <PageHeader eyebrow="Money in, cover on" title="Contribution ledger" description="Track what has landed, what is due, and where a gentle follow-up is needed." actions={<button data-testid="button-open-record-contribution" className="btn btn-primary" onClick={() => setOpen(true)}><Plus size={15} /> Record contribution</button>} />
    <div className="card p-3 mb-4 flex flex-col md:flex-row gap-2"><div className="relative flex-1"><Search size={15} className="absolute left-3 top-3 text-muted-foreground" /><input data-testid="input-contribution-search" className="input pl-9" placeholder="Search member or number" value={search} onChange={(e) => setSearch(e.target.value)} /></div><select data-testid="select-contribution-status" className="select md:w-48" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option><option value="paid">Paid</option><option value="due">Due</option><option value="overdue">Overdue</option></select><button data-testid="button-contribution-filters" className="btn btn-secondary" onClick={() => { setSearch(''); setStatus(''); }}><SlidersHorizontal size={15} /> Reset filters</button></div>
    <div className="card overflow-hidden">{contributionsQuery.isLoading ? <LoadingRows /> : contributionsQuery.isError ? <ErrorState onRetry={() => contributionsQuery.refetch()} /> : contributions.length === 0 ? <EmptyState title="No contribution records found" description="Try a different search or record the first payment." action={<button data-testid="button-record-empty-contribution" className="btn btn-primary" onClick={() => setOpen(true)}><Plus size={14} /> Record contribution</button>} /> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Member</th><th>Due date</th><th>Paid date</th><th>Amount</th><th>Method</th><th>Status</th></tr></thead><tbody>{contributions.map((item) => <tr key={item.id} data-testid={`row-contribution-${item.id}`}><td><div className="font-bold">{item.memberName}</div><div className="text-[11px] text-muted-foreground">{item.memberId}</div></td><td>{formatDate(item.dueDate)}</td><td>{formatDate(item.paidDate)}</td><td className="font-bold">{formatCurrency(item.amount)}</td><td className="capitalize">{item.method}</td><td><StatusBadge status={item.status} /></td></tr>)}</tbody></table></div>}</div>
    <div className="grid md:grid-cols-3 gap-4 mt-5"><div className="card p-4"><div className="stat-label">Showing</div><div className="text-2xl font-bold mt-2">{contributions.length}</div><div className="text-xs text-muted-foreground mt-1">ledger records</div></div><div className="card p-4"><div className="stat-label">Paid in view</div><div className="text-2xl font-bold mt-2">{formatCurrency(contributions.filter((item) => item.status === 'paid').reduce((sum, item) => sum + item.amount, 0))}</div><div className="text-xs text-muted-foreground mt-1">received contributions</div></div><div className="card p-4"><div className="stat-label">Needs attention</div><div className="text-2xl font-bold mt-2 text-destructive">{contributions.filter((item) => item.status === 'overdue').length}</div><div className="text-xs text-muted-foreground mt-1">overdue records</div></div></div>
    {open && <ContributionForm members={membersQuery.data ?? []} pending={recordContribution.isPending} onClose={() => setOpen(false)} onSubmit={(data) => recordContribution.mutate({ data }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: getListContributionsQueryKey() }); queryClient.invalidateQueries({ queryKey: getListMembersQueryKey() }); setOpen(false); } })} />}
  </div>;
}

function ContributionForm({ members, pending, onClose, onSubmit }: { members: { id: string; name: string; memberNumber: string; monthlyContribution: number }[]; pending: boolean; onClose: () => void; onSubmit: (data: ContributionInput) => void }) {
  const [form, setForm] = useState<ContributionInput>({ memberId: members[0]?.id ?? '', amount: members[0]?.monthlyContribution ?? 0, dueDate: new Date().toISOString().slice(0, 10), paidDate: new Date().toISOString().slice(0, 10), method: 'cash' });
  const selected = members.find((member) => member.id === form.memberId);
  return <Modal title="Record a contribution" description="Keep the ledger aligned with the receipt in hand." onClose={onClose}><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); onSubmit(form); }}><div><label className="label">Member</label><select data-testid="select-contribution-member" required className="select" value={form.memberId} onChange={(e) => { const member = members.find((item) => item.id === e.target.value); setForm((current) => ({ ...current, memberId: e.target.value, amount: member?.monthlyContribution ?? current.amount })); }}>{members.map((member) => <option key={member.id} value={member.id}>{member.name} · {member.memberNumber}</option>)}</select></div><div className="grid sm:grid-cols-2 gap-3"><div><label className="label">Amount</label><input data-testid="input-contribution-amount" required type="number" min="0.01" step="0.01" className="input" value={form.amount} onChange={(e) => setForm({ ...form, amount: Number(e.target.value) })} /></div><div><label className="label">Method</label><select data-testid="select-contribution-method" className="select" value={form.method} onChange={(e) => setForm({ ...form, method: e.target.value })}><option value="cash">Cash</option><option value="eft">EFT</option><option value="debit_order">Debit order</option><option value="card">Card</option></select></div><div><label className="label">Due date</label><input data-testid="input-contribution-due-date" required type="date" className="input" value={form.dueDate} onChange={(e) => setForm({ ...form, dueDate: e.target.value })} /></div><div><label className="label">Paid date</label><input data-testid="input-contribution-paid-date" type="date" className="input" value={form.paidDate ?? ''} onChange={(e) => setForm({ ...form, paidDate: e.target.value || null })} /></div></div><div className="rounded-lg bg-muted/60 p-3 text-xs text-muted-foreground flex items-center gap-2"><CircleDollarSign size={15} className="text-[hsl(var(--accent))]" /> Expected monthly amount: <span className="font-bold text-foreground">{formatCurrency(selected?.monthlyContribution ?? 0)}</span></div><div className="flex justify-end gap-2"><button data-testid="button-cancel-contribution" type="button" className="btn btn-secondary" onClick={onClose}>Cancel</button><button data-testid="button-save-contribution" className="btn btn-primary" disabled={pending || !form.memberId}>{pending ? 'Recording…' : 'Record payment'}</button></div></form></Modal>;
}
