import { ArrowLeft, Edit3, Mail, MapPin, Phone, Plus, Trash2, UserRound } from 'lucide-react';
import { useState } from 'react';
import { Link, useParams } from 'wouter';
import { useQueryClient } from '@tanstack/react-query';
import { getGetMemberQueryKey, useCreateBeneficiary, useDeleteBeneficiary, useGetMember, useUpdateBeneficiary, useUpdateMember } from '@workspace/api-client-react';
import type { Beneficiary, BeneficiaryInput, MemberUpdate } from '@workspace/api-client-react';
import { EmptyState, ErrorState, formatCurrency, formatDate, initials, LoadingRows, Modal, PageHeader, StatusBadge } from '@/components/ui';

export default function MemberProfilePage() {
  const params = useParams<{ memberId: string }>();
  const memberId = params.memberId ?? '';
  const queryClient = useQueryClient();
  const memberQuery = useGetMember(memberId, { query: { queryKey: getGetMemberQueryKey(memberId), enabled: Boolean(memberId) } });
  const updateMember = useUpdateMember();
  const createBeneficiary = useCreateBeneficiary();
  const updateBeneficiary = useUpdateBeneficiary();
  const deleteBeneficiary = useDeleteBeneficiary();
  const [editOpen, setEditOpen] = useState(false);
  const [beneficiaryOpen, setBeneficiaryOpen] = useState(false);
  const [editingBeneficiary, setEditingBeneficiary] = useState<Beneficiary | null>(null);
  const member = memberQuery.data;
  const invalidate = () => queryClient.invalidateQueries({ queryKey: getGetMemberQueryKey(memberId) });
  if (memberQuery.isLoading) return <div className="content-wrap"><LoadingRows count={7} /></div>;
  if (memberQuery.isError || !member) return <div className="content-wrap"><ErrorState onRetry={() => memberQuery.refetch()} /></div>;
  return <div className="content-wrap page-enter">
    <Link href="/members" data-testid="link-back-members" className="inline-flex items-center gap-2 text-xs text-muted-foreground hover:text-foreground mb-5"><ArrowLeft size={14} /> Back to directory</Link>
    <PageHeader eyebrow={member.memberNumber} title={member.name} description={`${member.planName} · Joined ${formatDate(member.joinedAt)}`} actions={<><StatusBadge status={member.status} /><button data-testid="button-edit-member" className="btn btn-secondary" onClick={() => setEditOpen(true)}><Edit3 size={14} /> Edit profile</button></>} />
    <div className="grid gap-5 lg:grid-cols-[.75fr_1.25fr]">
      <div className="space-y-5">
        <section className="card p-5"><div className="flex items-center gap-3 mb-5"><div className="avatar large">{initials(member.name)}</div><div><div className="font-bold">{member.name}</div><div className="text-xs text-muted-foreground">{member.branchName}</div></div></div><div className="space-y-4"><InfoRow icon={Phone} label="Phone" value={member.phone} /><InfoRow icon={Mail} label="Email" value={member.email} /><InfoRow icon={MapPin} label="Address" value={member.address} /><InfoRow icon={UserRound} label="ID number" value={member.idNumber} /></div></section>
        <section className="card p-5"><div className="flex items-center justify-between mb-4"><div><div className="section-title">Cover at a glance</div><div className="section-subtitle mt-1">The essentials for a quick conversation.</div></div><ShieldIcon /></div><div className="grid grid-cols-2 gap-3"><Metric label="Monthly contribution" value={formatCurrency(member.monthlyContribution)} /><Metric label="Dependants" value={`${member.dependantsCount}`} /><Metric label="Next due" value={formatDate(member.nextContributionDate)} /><Metric label="Plan" value={member.planName} /></div></section>
      </div>
      <div className="space-y-5">
        <section className="card overflow-hidden"><div className="p-5 flex justify-between items-start"><div><div className="section-title">Beneficiaries</div><div className="section-subtitle mt-1">People named to receive assistance.</div></div><button data-testid="button-add-beneficiary" className="btn btn-secondary" onClick={() => { setEditingBeneficiary(null); setBeneficiaryOpen(true); }}><Plus size={14} /> Add</button></div>{member.beneficiaries.length === 0 ? <EmptyState title="No beneficiaries recorded" description="Add a beneficiary before this record is complete." action={<button data-testid="button-add-first-beneficiary" className="btn btn-primary" onClick={() => { setEditingBeneficiary(null); setBeneficiaryOpen(true); }}>Add beneficiary</button>} /> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Name</th><th>Relationship</th><th>Allocation</th><th /></tr></thead><tbody>{member.beneficiaries.map((beneficiary) => <tr key={beneficiary.id} data-testid={`row-beneficiary-${beneficiary.id}`}><td><div className="font-bold">{beneficiary.name}</div><div className="text-[11px] text-muted-foreground">{beneficiary.phone}</div></td><td>{beneficiary.relationship}{beneficiary.primary && <span className="ml-2 text-[10px] text-[hsl(var(--accent))] font-bold">Primary</span>}</td><td>{beneficiary.allocation}%</td><td><div className="flex gap-1"><button data-testid={`button-edit-beneficiary-${beneficiary.id}`} className="btn btn-ghost p-2" onClick={() => { setEditingBeneficiary(beneficiary); setBeneficiaryOpen(true); }}><Edit3 size={14} /></button><button data-testid={`button-delete-beneficiary-${beneficiary.id}`} className="btn btn-ghost p-2 text-destructive" onClick={() => { if (window.confirm('Remove this beneficiary?')) deleteBeneficiary.mutate({ beneficiaryId: beneficiary.id }, { onSuccess: invalidate }); }}><Trash2 size={14} /></button></div></td></tr>)}</tbody></table></div>}</section>
        <section className="card overflow-hidden"><div className="p-5"><div className="section-title">Contribution history</div><div className="section-subtitle mt-1">Recent payment activity for this member.</div></div>{member.recentContributions.length === 0 ? <EmptyState title="No contributions recorded" description="Payment history will appear after the first contribution." /> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Due</th><th>Paid</th><th>Amount</th><th>Method</th><th>Status</th></tr></thead><tbody>{member.recentContributions.map((item) => <tr key={item.id}><td>{formatDate(item.dueDate)}</td><td>{formatDate(item.paidDate)}</td><td className="font-bold">{formatCurrency(item.amount)}</td><td>{item.method}</td><td><StatusBadge status={item.status} /></td></tr>)}</tbody></table></div>}</section>
        <section className="card overflow-hidden"><div className="p-5"><div className="section-title">Funeral assistance claims</div><div className="section-subtitle mt-1">Claims associated with this member.</div></div>{member.recentClaims.length === 0 ? <EmptyState title="No claims recorded" description="There are no claims associated with this member." /> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Claim</th><th>Deceased</th><th>Amount</th><th>Status</th></tr></thead><tbody>{member.recentClaims.map((claim) => <tr key={claim.id}><td><div className="font-bold">{claim.claimNumber}</div><div className="text-[11px] text-muted-foreground">{formatDate(claim.submittedAt)}</div></td><td>{claim.deceasedName}</td><td className="font-bold">{formatCurrency(claim.amount)}</td><td><StatusBadge status={claim.status} /></td></tr>)}</tbody></table></div>}</section>
      </div>
    </div>
    {editOpen && <MemberEditForm member={member} pending={updateMember.isPending} onClose={() => setEditOpen(false)} onSubmit={(data) => updateMember.mutate({ memberId, data }, { onSuccess: () => { invalidate(); setEditOpen(false); } })} />}
    {beneficiaryOpen && <BeneficiaryForm memberId={memberId} initial={editingBeneficiary} pending={createBeneficiary.isPending || updateBeneficiary.isPending} onClose={() => setBeneficiaryOpen(false)} onSubmit={(data) => { if (editingBeneficiary) { updateBeneficiary.mutate({ beneficiaryId: editingBeneficiary.id, data }, { onSuccess: () => { invalidate(); setBeneficiaryOpen(false); } }); } else { createBeneficiary.mutate({ memberId, data }, { onSuccess: () => { invalidate(); setBeneficiaryOpen(false); } }); } }} />}
  </div>;
}

function InfoRow({ icon: Icon, label, value }: { icon: typeof Phone; label: string; value: string }) { return <div className="flex gap-3"><Icon size={15} className="text-muted-foreground mt-0.5" /><div><div className="label mb-0">{label}</div><div className="text-sm">{value || 'Not supplied'}</div></div></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-muted/60 p-3"><div className="text-[10px] text-muted-foreground uppercase tracking-wider">{label}</div><div className="text-sm font-bold mt-2 break-words">{value}</div></div>; }
function ShieldIcon() { return <div className="w-8 h-8 rounded-full bg-secondary grid place-items-center text-primary"><UserRound size={15} /></div>; }

function MemberEditForm({ member, pending, onClose, onSubmit }: { member: { name: string; phone: string; email: string; address: string; idNumber: string; planName: string; status: string }; pending: boolean; onClose: () => void; onSubmit: (data: MemberUpdate) => void }) {
  const [form, setForm] = useState<MemberUpdate>({ name: member.name, phone: member.phone, email: member.email, address: member.address, idNumber: member.idNumber, planName: member.planName, status: member.status as MemberUpdate['status'] });
  const set = (key: keyof MemberUpdate, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <Modal title="Edit member profile" description="Keep the core record accurate and current." onClose={onClose}><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); onSubmit(form); }}><div className="grid sm:grid-cols-2 gap-3"><div><label className="label">Full name</label><input data-testid="input-edit-member-name" className="input" value={form.name ?? ''} onChange={(e) => set('name', e.target.value)} /></div><div><label className="label">Phone</label><input data-testid="input-edit-member-phone" className="input" value={form.phone ?? ''} onChange={(e) => set('phone', e.target.value)} /></div><div><label className="label">Email</label><input data-testid="input-edit-member-email" className="input" value={form.email ?? ''} onChange={(e) => set('email', e.target.value)} /></div><div><label className="label">Plan</label><select data-testid="select-edit-member-plan" className="select" value={form.planName ?? ''} onChange={(e) => set('planName', e.target.value)}><option>Family Cover</option><option>Individual Cover</option><option>Premium Family Cover</option></select></div></div><div><label className="label">Address</label><input data-testid="input-edit-member-address" className="input" value={form.address ?? ''} onChange={(e) => set('address', e.target.value)} /></div><div><label className="label">Status</label><select data-testid="select-edit-member-status" className="select" value={form.status ?? ''} onChange={(e) => set('status', e.target.value)}><option value="active">Active</option><option value="pending">Pending</option><option value="lapsed">Lapsed</option><option value="deceased">Deceased</option></select></div><div className="flex justify-end gap-2"><button data-testid="button-cancel-edit-member" type="button" className="btn btn-secondary" onClick={onClose}>Cancel</button><button data-testid="button-save-member" className="btn btn-primary" disabled={pending}>{pending ? 'Saving…' : 'Save changes'}</button></div></form></Modal>;
}

function BeneficiaryForm({ memberId, initial, pending, onClose, onSubmit }: { memberId: string; initial: Beneficiary | null; pending: boolean; onClose: () => void; onSubmit: (data: BeneficiaryInput) => void }) {
  const [form, setForm] = useState<BeneficiaryInput>({ name: initial?.name ?? '', relationship: initial?.relationship ?? '', phone: initial?.phone ?? '', allocation: initial?.allocation ?? 50, primary: initial?.primary ?? false });
  const set = (key: keyof BeneficiaryInput, value: string | boolean | number) => setForm((current) => ({ ...current, [key]: value }));
  return <Modal title={initial ? 'Edit beneficiary' : 'Add beneficiary'} description={`${initial ? 'Updating' : 'Adding to'} member ${memberId}`} onClose={onClose}><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); onSubmit(form); }}><div className="grid sm:grid-cols-2 gap-3"><div><label className="label">Full name</label><input data-testid="input-beneficiary-name" required className="input" value={form.name} onChange={(e) => set('name', e.target.value)} /></div><div><label className="label">Relationship</label><input data-testid="input-beneficiary-relationship" required className="input" value={form.relationship} onChange={(e) => set('relationship', e.target.value)} /></div><div><label className="label">Phone</label><input data-testid="input-beneficiary-phone" required className="input" value={form.phone} onChange={(e) => set('phone', e.target.value)} /></div><div><label className="label">Allocation (%)</label><input data-testid="input-beneficiary-allocation" required type="number" min="1" max="100" className="input" value={form.allocation} onChange={(e) => set('allocation', Number(e.target.value))} /></div></div><label className="flex items-center gap-2 text-xs font-semibold"><input data-testid="checkbox-beneficiary-primary" type="checkbox" checked={form.primary} onChange={(e) => set('primary', e.target.checked)} /> Mark as primary beneficiary</label><div className="flex justify-end gap-2"><button data-testid="button-cancel-beneficiary" type="button" className="btn btn-secondary" onClick={onClose}>Cancel</button><button data-testid="button-save-beneficiary" className="btn btn-primary" disabled={pending}>{pending ? 'Saving…' : initial ? 'Save beneficiary' : 'Add beneficiary'}</button></div></form></Modal>;
}
